CREATE TABLE IF NOT EXISTS Usersdb.Users (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
UserAgent VARCHAR(256) NOT NULL,IP VARCHAR(30) NOT NULL,
CanvasId VARCHAR(8),
LastVisit DATETIME, Count INT);

CREATE TABLE IF NOT EXISTS Usersdb.Products (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Company VARCHAR(128) NOT NULL,Phone VARCHAR(40) NOT NULL,
Price DECIMAL(4,2) NOT NULL,InStock BOOLEAN NOT NULL,
StockCount INT,NewStockDate  DATETIME);




