version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

  #DataBase Service
  database:
    #Pull the latest mysql image
    image: mysql:8.0.26
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    #Map port 3306 on the mysql container to port 3306 in the host
    ports:
      - "3306:3306"
    #Specify where the persisted Data should be stored
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    #Specify Environment Variables for mysql
    environment:
      MYSQL_ROOT_PASSWORD: Root0++
      MYSQL_USER: newuser
      MYSQL_PASSWORD: M0use!in99
      MYSQL_DATABASE: Usersdb