name: old shh flow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test_build:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: testdb
      DB_USER: root
      DB_PASSWORD: "root"
      DB_HOST: localhost
      ASPNETCORE_ENVIRONMENT: Development

    steps:
      - run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE testdb;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot

      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
      - name: Run SQL script
        run: |
          mysql  -uroot -proot < "setup.sql"
      - name: Restore dependencies
        run: |
          dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

      #- name: variable substitution in json
      #  uses: microsoft/variable-substitution@v1 
      #  with:
      #   files: './src/MyAPI/appsettings.json'  
      #  env:
      #    ConnectionStrings.MySqlDB: ${{ secrets.CONNECTIONSTRING }}
      #    url: https://github.com/${{github.repository}}

   
      - name: run commands via SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd ..
            cd DocsAPI/src/MyAPI
            git pull
            docker-compose -f docker-compose.prod.yml up --build -d
          # rm -rf DocsAPI
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.username }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true

    # create gihub action to build and run tests using dotnet
    #     git clone https://sajrashid:${{secrets.GITREPOTOKEN}}@github.com/sajrashid/DocsAPI.git
    # curl to api test 